In [1]:
import pandas as pd

In [6]:
# mixtral_temp0 = pd.read_csv('./results/concept_repr/ebay_us_desc_Mixtral-temp0.csv')
# mixtral_temp005 = pd.read_csv('./results/concept_repr/ebay_us_desc_Mixtral-temp0.05.csv')
# qwen_temp0 = pd.read_csv('./results/concept_repr/ebay_us_desc_Qwen-temp0.csv')
# qwen_temp005 = pd.read_csv('./results/concept_repr/ebay_us_desc_Qwen-temp0.05.csv')
raw_out = pd.read_csv('./results/concept_repr/krylov_out_20240911-1114.csv')

In [7]:
out = raw_out[['ID', 'name', 'pred']].rename({'pred': 'desc'})

In [8]:
out

,ID,name,pred
0,1,Collectibles,Collectibles is a diverse category that includ...
1,20081,Antiques,Antiques is a category that encompasses a wide...
2,12,Other Antiques,Other Antiques is a category for items that do...
3,1430,Collectible Metalware,Collectible Metalware is a category featuring ...
4,28,Other Collectible Metalware,Other Collectible Metalware is a diverse categ...
...,...,...,...
20329,263470,"ATV, Side-by-Side & UTV Gaskets & Seals","ATV, Side-by-Side & UTV Gaskets & Seals is a c..."
20330,263471,"ATV, Side-by-Side & UTV Brake Blockoffs","ATV, Side-by-Side & UTV Brake Blockoffs is a c..."
20331,263472,"ATV, Side-by-Side & UTV Brake Component Kits","ATV, Side-by-Side & UTV Brake Component Kits i..."
20332,263473,"ATV, Side-by-Side & UTV Rebuild Kits & Parts","ATV, Side-by-Side & UTV Rebuild Kits & Parts i..."
20333,0,Root Concept,Root Concept is a broad category that encompas...

In [9]:
out.to_csv('./results/concept_repr/ebay_us_desc_Qwen_temp0_20item.csv', index=False)

In [2]:
mixtral_temp0 = pd.read_csv('./results/concept_repr/ebay_us_desc_Mixtral_temp0_20item.csv')
qwen_temp0 = pd.read_csv('./results/concept_repr/ebay_us_desc_Qwen_temp0_20item.csv')

In [3]:
def bad(text):
    return '\n' in text

In [4]:
mixtral_temp0_bad = mixtral_temp0[mixtral_temp0['pred'].apply(bad)]
qwen_temp0_bad = qwen_temp0[qwen_temp0['pred'].apply(bad)]

In [5]:
mixtral_temp0_bad

,ID,name,pred
4372,31875,Volkswagen Cabrio,Volkswagen Cabrio is a category of convert...
8456,84153,Acura TSX,Acura TSX is a category of sedans produced...
8464,84161,Mazda Tribute,Mazda Tribute is a category of automobiles...
13778,177695,Fisker Karma,Fisker Karma is a category of luxury elect...
15201,181467,Lexus RC,Lexus RC is a category of luxury sports ca...
19458,261799,Gymnastics Air Pumps,Gymnastics Air Pumps is a category that in...

In [6]:
qwen_temp0_bad.

,ID,name,pred
6,717,Vintage & Antique Toys,Vintage & Antique Toys is a category that enco...
13,37,Other Soda Merchandise & Memorabilia,Other Soda Merchandise & Memorabilia is a cate...
28,53,Other MLB Autographed Items,Other MLB Autographed Items is a category for ...
44,114,Other Sewing Collectibles,Other Sewing Collectibles is a category for vi...
45,41192,Collectible Sewing Buttons,Collectible Sewing Buttons is a category for u...
...,...,...,...
20140,263263,"Electric ATV, SxS & UTV Charging Converters","Electric ATV, SxS & UTV Charging Converters is..."
20148,263271,"Electric ATV, SxS & UTV Heatsinks & Cooling Fins","Electric ATV, SxS & UTV Heatsinks & Cooling Fi..."
20257,263388,"ATV, Side-by-Side & UTV Engine Sensors & Switches","ATV, Side-by-Side & UTV Engine Sensors & Switc..."
20266,263397,"ATV, Side-by-Side & UTV Pistons, Rings & Pisto...","ATV, Side-by-Side & UTV Pistons, Rings & Pisto..."
20312,263451,"ATV, Side-by-Side & UTV Primary Drive Kits","ATV, Side-by-Side & UTV Primary Drive Kits is ..."